name: Count Files in Directory

on:
  push:
    branches:
      - main # Replace 'main' with your repository's default branch name

jobs:
  count-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Count Files
      run: |
        files_count=$(find Button/SVG -type f | wc -l)
        echo "{\"files_count\": $files_count}" > files_count.json

    - name: Commit Files Count to Repository
      run: |
        git config user.name "TakiShiwa"
        git config user.email "judhistiram@protonmail.com"
        git add files_count.json
        git commit -m "Update files_count.json with the latest count"
        git push
