name: Generate Badge

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Count Files
        id: count_files
        run: |
          directory_to_count="Button/SVG"
          file_count=$(find "$directory_to_count" -type f | wc -l)
          echo "$file_count" > badge_value.txt

      - name: Set Badge Value
        id: set_badge_value
        run: |
          echo "::set-output name=badge_value::$(cat badge_value.txt)"

      - name: Display Badge
        run: |
          echo "![Files Count](https://img.shields.io/badge/dynamic/json?color=blue&label=Files&query=\$.message&url=https://TakiShiwa.github.io/donate-with-upi/badge.json&cacheSeconds=3600)" > README.md
          cat badge_value.txt >> README.md
