name: Update File Count

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Count Files
        run: |
          directory_to_count="Button/SVG"
          file_count=$(find "$directory_to_count" -type f | wc -l)
          echo "{\"schemaVersion\": 1, \"label\": \"Files\", \"message\": \"$file_count\", \"color\": \"blue\"}" > files_count.json

      - name: Commit Files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add files_count.json
          git commit -m "Update file count [skip ci]"
          git push
