name: Update File Count Badge

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Count Files
        id: count_files
        run: |
          DIRECTORY_PATH="Button/SVG"
          FILE_COUNT=$(find "$DIRECTORY_PATH" -type f | wc -l)
          echo "::set-output name=count::$FILE_COUNT"

      - name: Update Badge
        uses: shieldsio/github-action@master
        with:
          path: ${{ github.repository }}
          key: files
          value: ${{ steps.count_files.outputs.count }}
