name: Update File Count Badge

on:
  push:
    branches:
      - main

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Count Files
        id: count_files
        run: |
          chmod +x count_files.sh
          FILE_COUNT=$(./count_files.sh)
          echo "FILE_COUNT=$FILE_COUNT" >> $GITHUB_ENV
          echo "::set-output name=FILE_COUNT::$FILE_COUNT"

      - name: Update Badge
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          FILE_COUNT: ${{ needs.update-badge.outputs.file-count }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout gh-pages
          echo '{"message": "'"$FILE_COUNT"'"}' > badge.json
          git add badge.json
          git commit -m "Update file count badge: $FILE_COUNT files"
          git push origin gh-pages
