name: Generate File Count Badge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Create File Count Badge
        id: create_badge
        run: node file-counter/index.js

      - name: Use Badge Data
        id: badge_data
        run: echo ::set-output name=badge_data::${{ steps.create_badge.outputs.stdout }}

      - name: Display Badge Data
        run: echo ${{ steps.badge_data.outputs.badge_data }} > file-count.json

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add file-count.json
          git commit -m "Update file count badge"
          git push origin main
