name: Update File Count

on:
  push:
    branches:
      - main 

jobs:
  update_count:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Count files and update JSON
        run: |
          FILE_COUNT=$(find Button/SVG -type f | wc -l)
          echo "{\"file_count\": $FILE_COUNT}" > file_count.json

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add file_count.json
          git commit -m "Update file count [skip ci]"
          git push origin main
